<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Ralf Becker" />

<meta name="date" content="2018-11-29" />

<title>Introduction to Data Handling and Statistics</title>

<script src="Data_Intro_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="Data_Intro_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="Data_Intro_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="Data_Intro_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="Data_Intro_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="Data_Intro_files/navigation-1.1/tabsets.js"></script>
<link href="Data_Intro_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="Data_Intro_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Introduction to Data Handling and Statistics</h1>
<h4 class="author"><em>Ralf Becker</em></h4>
<h4 class="date"><em>29 November 2018</em></h4>

</div>


<div id="preparing-your-workfile" class="section level1">
<h1>Preparing your workfile</h1>
<p>R is a powerful software for statistical analysis. It is open source and hence FREE software. It is constantly developped and functionality is being improved. The “price” we pay for this is that we have to do a little more set-up work to make it work.</p>
<p>In particular we need packages which are provided for free by researchers/programmers that provide useful functionality.</p>
<p>But we add libraries which enhance its capabilities.</p>
<pre class="r"><code>library(tidyverse)    # for almost all data handling tasks</code></pre>
<pre><code>## Warning: package &#39;tidyverse&#39; was built under R version 3.5.1</code></pre>
<pre><code>## -- Attaching packages -------------------------------------------------------------------------------- tidyverse 1.2.1 --</code></pre>
<pre><code>## v ggplot2 2.2.1     v purrr   0.2.4
## v tibble  1.4.2     v dplyr   0.7.4
## v tidyr   0.8.0     v stringr 1.3.0
## v readr   1.1.1     v forcats 0.3.0</code></pre>
<pre><code>## -- Conflicts ----------------------------------------------------------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(readxl)       # to import Excel data</code></pre>
<pre><code>## Warning: package &#39;readxl&#39; was built under R version 3.5.1</code></pre>
<pre class="r"><code>library(ggplot2)      # to produce nice graphiscs
library(stargazer)    # to produce nice results tables</code></pre>
<pre><code>## 
## Please cite as:</code></pre>
<pre><code>##  Hlavac, Marek (2018). stargazer: Well-Formatted Regression and Summary Statistics Tables.</code></pre>
<pre><code>##  R package version 5.2.2. https://CRAN.R-project.org/package=stargazer</code></pre>
</div>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>Here we use an example which, at the time, made a lot of waves. Carmen Reinhart and Kenneth Rogoff (2010) wrote work that attempted to examine the <a href="https://scholar.harvard.edu/files/rogoff/files/growth_in_time_debt_aer.pdf">relationship between Debt to GDP levels and GDP growth</a>. Their general conclusion was that, as long as the debt to GDP ration does not exceed 90% there seems to be no clear relationship between the two. However, countries eunning higher debt to GDP ratios are paying a sizeable growth penalty.</p>
<p>The empirical work of Reinhard and Rogoff was critised on three aspects by Thomas Herndon, Michael Ash and Robert Pollin. This work was published in the <a href="https://academic.oup.com/cje/article-abstract/38/2/257/1714018?redirectedFrom=fulltext">Cambridge Journal of Economics in 2014</a> and previous to that as a working paper. The <a href="https://www.peri.umass.edu/publication/item/526-does-high-public-debt-consistently-stifle-economic-growth-a-critique-of-reinhart-and-rogoff">working paper’s website</a> also contains all the relevant data and code.</p>
</div>
<div id="importing-data" class="section level1">
<h1>Importing Data</h1>
<p>This is a simplified spreadsheet (based on the work of Herndon et al.)</p>
<pre class="r"><code>RRData &lt;- read_excel(&quot;RRdata.xlsx&quot;)
RRData &lt;- as.data.frame(RRData)
str(RRData)  # prints some basic info on variables</code></pre>
<pre><code>## &#39;data.frame&#39;:    1171 obs. of  4 variables:
##  $ Year   : num  1946 1947 1948 1949 1950 ...
##  $ Country: chr  &quot;Australia&quot; &quot;Australia&quot; &quot;Australia&quot; &quot;Australia&quot; ...
##  $ debtgdp: num  190 177 149 126 110 ...
##  $ dRGDP  : num  -3.56 2.46 6.44 6.61 6.92 ...</code></pre>
<p>We can see that three variables are numeric (<code>num</code>) variables which is as we expect. The fourth variable <code>Country</code> is labeled as a character (<code>chr</code>) variable, basically text. It will pay off for later to indicate to R that this is a categorical (nominal) variable. This is done as follows:</p>
<pre class="r"><code>RRData$Country &lt;- as.factor(RRData$Country)
str(RRData)</code></pre>
<pre><code>## &#39;data.frame&#39;:    1171 obs. of  4 variables:
##  $ Year   : num  1946 1947 1948 1949 1950 ...
##  $ Country: Factor w/ 20 levels &quot;Australia&quot;,&quot;Austria&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ debtgdp: num  190 177 149 126 110 ...
##  $ dRGDP  : num  -3.56 2.46 6.44 6.61 6.92 ...</code></pre>
<p>There are 1171 country-year observations. In the dataset are data from 20 countries:</p>
<pre class="r"><code>unique(RRData$Country)</code></pre>
<pre><code>##  [1] Australia   Austria     Belgium     Canada      Denmark    
##  [6] Finland     France      Germany     Greece      Ireland    
## [11] Italy       Japan       Netherlands New Zealand Norway     
## [16] Portugal    Spain       Sweden      UK          US         
## 20 Levels: Australia Austria Belgium Canada Denmark Finland ... US</code></pre>
<p>And data from 1946 to 2009.</p>
<pre class="r"><code>summary(RRData$Year)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1946    1964    1980    1979    1995    2009</code></pre>
<p><code>debtgdp</code> is the debt to GDP ratio</p>
<pre class="r"><code>summary(RRData$debtgdp)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   3.279  22.148  40.401  46.283  61.474 247.482</code></pre>
<p><code>dRGDP</code> is GDP growth rate</p>
<pre class="r"><code>summary(RRData$dRGDP)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -10.942   1.911   3.283   3.430   5.100  27.329</code></pre>
<p>The typical <code>summary</code> output does not include two pieces of info which we would often like to see, the number of observations and the standard deviation. To the rescue comes the <code>stargazer</code> package.</p>
<pre class="r"><code>stargazer(RRData,type=&quot;text&quot;) # other types available: &quot;latex&quot;, &quot;html&quot;</code></pre>
<pre><code>## 
## ====================================================================
## Statistic   N     Mean    St. Dev.   Min   Pctl(25) Pctl(75)   Max  
## --------------------------------------------------------------------
## Year      1,171 1,979.155  17.944   1,946   1,964    1,995    2,009 
## debtgdp   1,171  46.283    32.395   3.279   22.148   61.474  247.482
## dRGDP     1,171   3.430    2.981   -10.942  1.911    5.100   27.329 
## --------------------------------------------------------------------</code></pre>
</div>
<div id="an-initial-basic-data-plots" class="section level1">
<h1>An initial basic data plots</h1>
<p>Let’s have a look at some of the data. We will first look at a scatterplot (using the amazing <code>ggplot</code> library).</p>
<pre class="r"><code>ggplot(RRData,aes(x=debtgdp,y=dRGDP)) +
  geom_point() +    # this produces the scatter plot
  geom_smooth(method = &quot;lm&quot;, se = FALSE)  # this adds the linear line of best fit</code></pre>
<p><img src="Data_Intro_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Note a few points about how this graph is being called. <code>ggplot(RRData,aes(debtgdp,dRGDP))</code> Sets up the graph. The first input (<code>RRData</code>) tells R which data to use. In the <code>aes()</code> section (<code>aes</code> for aesthetics) we determine which variable should appear on the x-axis (<code>x=debtgdp</code>) and which is to go onto the y-axis (<code>y=dRGDP</code>). At this stage we havn’t actually produced a graph yet, we just did the ground work. Then we add the graph we want, here a scatterplot, in R <code>geom_point()</code>. As you can see, the first line and the second line are linked with a <code>+</code>. This has to come at the end of the first line so that R knows that it should expect more information. The last line (again attached to the previous line via a <code>+</code>) <code>geom_smooth(method = &quot;lm&quot;, se = FALSE)</code> adds the regression line (<code>lm</code> = linear model). Try what happens if you take out <code>, se = FALSE</code>.</p>
<p>We could actually run this regression:</p>
<pre class="r"><code>mod1 &lt;- lm(dRGDP~debtgdp, data= RRData)
summary(mod1)   # this is the standard R way for results</code></pre>
<pre><code>## 
## Call:
## lm(formula = dRGDP ~ debtgdp, data = RRData)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -12.9958  -1.5200  -0.0774   1.5707  23.6960 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  4.279290   0.148970   28.73  &lt; 2e-16 ***
## debtgdp     -0.018355   0.002637   -6.96 5.67e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.922 on 1169 degrees of freedom
## Multiple R-squared:  0.03979,    Adjusted R-squared:  0.03897 
## F-statistic: 48.44 on 1 and 1169 DF,  p-value: 5.666e-12</code></pre>
<pre class="r"><code>stargazer(mod1,type=&quot;text&quot;) # a nicer way</code></pre>
<pre><code>## 
## ===============================================
##                         Dependent variable:    
##                     ---------------------------
##                                dRGDP           
## -----------------------------------------------
## debtgdp                      -0.018***         
##                               (0.003)          
##                                                
## Constant                     4.279***          
##                               (0.149)          
##                                                
## -----------------------------------------------
## Observations                   1,171           
## R2                             0.040           
## Adjusted R2                    0.039           
## Residual Std. Error      2.922 (df = 1169)     
## F Statistic          48.439*** (df = 1; 1169)  
## ===============================================
## Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<p>There are issues with running a regression like this. Perhaps most importantly that the observations cannot be argued to be independent. The growth rate and debt to GDP ratios of, say, the UK in 1981 is clearly not independent of the data in 1980. In particular debt to GDP ratios are slow moving data.</p>
<p>To illustrate this point we should look at the data as time series.</p>
<pre class="r"><code>tempdata &lt;- RRData %&gt;% filter(Country %in% c(&quot;Germany&quot;,&quot;Greece&quot;,&quot;UK&quot;,&quot;US&quot;))
ggplot(tempdata,aes(Year,debtgdp,color=Country)) +
  geom_line()     # this produces the line plot</code></pre>
<p><img src="Data_Intro_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre class="r"><code>tempdata &lt;- RRData %&gt;% filter(Country %in% c(&quot;Germany&quot;,&quot;Greece&quot;,&quot;UK&quot;,&quot;US&quot;))
ggplot(tempdata,aes(Year,dRGDP,color=Country)) +
  geom_line(size=1)     # this produces the line plot</code></pre>
<p><img src="Data_Intro_files/figure-html/unnamed-chunk-11-2.png" width="672" /></p>
<p>You can clearly see that the <code>debtgdp</code> data, from year to year, are dependent. Also, the <code>dRGDP</code> plot reveals that there is a fair bit of correlation between the growth rates in economies.</p>
</div>
<div id="some-data-cuts" class="section level1">
<h1>Some data cuts</h1>
<p>Let’s look at the data for a few countries</p>
<pre class="r"><code>tempdata &lt;- RRData %&gt;% filter(Country %in% c(&quot;Germany&quot;,&quot;Greece&quot;,&quot;UK&quot;,&quot;US&quot;))
ggplot(tempdata,aes(debtgdp,dRGDP,color=Country)) +
  geom_point()     # this produces the scatter plot</code></pre>
<p><img src="Data_Intro_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>From here you can see that different countries appear to have quite different patterns.</p>
<p>Let’s calculate average and median growth rates and debt to gdp ratios for these countries. To achieve this we will first group the data by Country <code>group_by(Country)</code> and then summarise the variables <code>dRGDP</code> and <code>debtgdp</code> (<code>summarise_at(c(&quot;dRGDP&quot;, &quot;debtgdp&quot;), ...)</code>) in the resulting groups by applying the mean and median function (<code>funs(mean, median, sd)</code>).</p>
<pre class="r"><code>tempdata %&gt;% group_by(Country) %&gt;% 
            summarise_at(c(&quot;dRGDP&quot;, &quot;debtgdp&quot;), funs(mean, median,sd)) %&gt;% 
            print()</code></pre>
<pre><code>## # A tibble: 4 x 7
##   Country dRGDP_mean debtgdp_mean dRGDP_median debtgdp_median dRGDP_sd
##   &lt;fct&gt;        &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;          &lt;dbl&gt;    &lt;dbl&gt;
## 1 Germany       3.31         17.8         2.88           14.9     2.91
## 2 Greece        2.93         67.7         3.39           77.5     3.11
## 3 UK            2.41         78.7         2.68           47.6     1.90
## 4 US            3.00         56.0         3.38           56.3     3.04
## # ... with 1 more variable: debtgdp_sd &lt;dbl&gt;</code></pre>
</div>
<div id="create-categorical-debt-to-gdp-ratios---reinhard-rogoff-analysis-i" class="section level1">
<h1>Create categorical debt to GDP ratios - Reinhard-Rogoff analysis I</h1>
<p>In order to replicate some of the analysis in Reinhard and Rogoff and the subsequent critique in Herndon et al. we will want to create categorical variables for the Debt to GDP ratio. In other words we want to</p>
<pre class="r"><code>RRData &lt;- RRData %&gt;% mutate(dgcat = cut(RRData$debtgdp, breaks=c(0,30,60,90,Inf)))

RRData %&gt;% group_by(dgcat) %&gt;% 
            summarise_at(&quot;dRGDP&quot;, funs(mean, median)) %&gt;% 
            print()</code></pre>
<pre><code>## # A tibble: 4 x 3
##   dgcat     mean median
##   &lt;fct&gt;    &lt;dbl&gt;  &lt;dbl&gt;
## 1 (0,30]    4.17   4.15
## 2 (30,60]   3.12   3.11
## 3 (60,90]   3.22   2.9 
## 4 (90,Inf]  2.17   2.34</code></pre>
</div>
<div id="hypothesis-testing---means-and-differences-in-mean" class="section level1">
<h1>Hypothesis Testing - means and differences in mean</h1>
<p>Hypothesis testing is at the core of much empirical analysis. Here we will show how to perform hyothesis tests. We are using the <code>t.test</code> function. Often hypothesis tests will be testing hypotheses about the mean of a random variable. We also learn how to perform hypothesis on regression coefficients (often these are nothing else but ways to estimate means!).</p>
<p>Let’s start by testing a hypothesis on the sample mean of the GDP growth rate (<code>dRGDP</code>) Let’s say we want to test the hypothesis that the mean growth rate is 3.3% (note that 3.3% in the dat aiis represented as 3.3). Let’s get one calculated and then diiscuss what we really did:</p>
<pre class="r"><code>t.test(RRData$dRGDP, mu=3.3)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  RRData$dRGDP
## t = 1.4896, df = 1170, p-value = 0.1366
## alternative hypothesis: true mean is not equal to 3.3
## 95 percent confidence interval:
##  3.258847 3.600675
## sample estimates:
## mean of x 
##  3.429761</code></pre>
<p>You may remember that, in order to perform a hypothesis test you, the applied economist, has to set the null (<span class="math inline">\(H_0\)</span>) and alternative (<span class="math inline">\(H_A\)</span>) hypothesis. Here you set the null hypothesis that the mean (<code>mu</code>) is equal to 3 (<span class="math inline">\(H_0\)</span>:<code>mu=3.3</code>). You also need to specify an alternative hypothesis. We didn’t specify any so R (or better <code>t.test</code>) used it’s default option, two sided alternative (<span class="math inline">\(H_A: mu \neq 3.3\)</span>).</p>
<p>The judgemment here is that it is possible that the true, yet unknown population mean is equal to 3.3. The test statistic is 1.4896 and the p-value is 0.1366. Only if the p-value is smaller than our chosen level of significance (often 0.01, 0.05 or 0.1) would we reject the null hypothesis <span class="math inline">\(H_0\)</span>.</p>
<p>Make sure you use the help function (type <code>?t.test</code> into the command window) or search for help (type “R t.test” into your favourite search engine) to understand more details of the function.</p>
<p>Let’s calculate a one sided test with the alternative that (<span class="math inline">\(H_A: mu &gt; 3.3\)</span>):</p>
<pre class="r"><code>t.test(RRData$dRGDP, mu=3.3, alternative=&quot;greater&quot;)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  RRData$dRGDP
## t = 1.4896, df = 1170, p-value = 0.0683
## alternative hypothesis: true mean is greater than 3.3
## 95 percent confidence interval:
##  3.28636     Inf
## sample estimates:
## mean of x 
##  3.429761</code></pre>
<p>Changing the alternative does not change the t-test but change the p-value. Now the p-value is 0.0683 and whether we reject or do not reject <span class="math inline">\(H_0\)</span> depends on our chosen significance level.</p>
<p>At this stage a we need to mention a huge caveat to the above tests. Our standard tests are based on the assumption that the data are identically and independently distributed. In some sense we have already seen that the this assumption cannot be defended with the data at hand. We saw the time-series plot above which showed that observations are correlated between years and ountries, so they are not independent observations. But let’s, for the sake of this introduction, ignore this complication, but note that we need to interpret results with caution.</p>
<p>Above we sliced the data into different subsets. Let’s use the debt level categories and compare means of growth between the subsets.</p>
<pre class="r"><code>temp_high &lt;- RRData %&gt;% filter(dgcat == &quot;(90,Inf]&quot;)
temp_middle &lt;- RRData %&gt;% filter(dgcat == &quot;(60,90]&quot;)

t.test(temp_high$dRGDP,temp_middle$dRGDP)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  temp_high$dRGDP and temp_middle$dRGDP
## t = -2.7221, df = 184.28, p-value = 0.007109
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1.817628 -0.290037
## sample estimates:
## mean of x mean of y 
##  2.167972  3.221804</code></pre>
<p>At the bottom of the output you can see the respective sample means (which replicates the sample means we printed earlier in a table). The hyothesis tested is <span class="math inline">\(H_0: mu_{high}=mu_{middle}\)</span> with the alternative that the respective population means are different (<span class="math inline">\(H_a:mu_{high}\neq mu_{middle}\)</span>). As above we could have elected to test an alternative of <span class="math inline">\(&gt;\)</span> or <span class="math inline">\(&lt;\)</span> as well.</p>
<p>So yes there seems to be some negative correlation between the level of debt and the economic growth. So what was all the fuss about?</p>
</div>
<div id="reinhard-rogoff-analysis-ii" class="section level1">
<h1>Reinhard-Rogoff Analysis II</h1>
<p>The reason why the work by Reinhard and Rogoff was so controversial was that it wasn’t the numbers as reported above they published. They reported numbers after changing the dataset as follows:</p>
<ol style="list-style-type: decimal">
<li>They excluded early-postwar data for New Zealand, Australia and Canada, arguing that these data are atypical for later periods, essentially they are outliers</li>
</ol>
<pre class="r"><code>## Selective treatment of early years

RRselective &lt;- RRData %&gt;% filter(!((Year&lt;1950 &amp; Country==&quot;New Zealand&quot;) | (Year&lt;1951 &amp; Country==&quot;Australia&quot;) | (Year&lt;1951 &amp; Country==&quot;Canada&quot;) ))</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>A spreadsheet error resulted in data for the five countries (Australia, Austria, Belgium, Canada and Denmark) to not be included:</li>
</ol>
<pre class="r"><code>RRselective &lt;- RRselective %&gt;% filter(!( Country %in% c(&quot;Australia&quot;,&quot;Austria&quot;,&quot;Belgium&quot;,&quot;Canada&quot;,&quot;Denmark&quot;) ))</code></pre>
<p>And now we repeat the mean and median calculations we performed above on teh complete dataset.</p>
<pre class="r"><code>RRselective %&gt;% group_by(dgcat) %&gt;% 
            summarise_at(&quot;dRGDP&quot;, funs(mean, median)) %&gt;% 
            print()</code></pre>
<pre><code>## # A tibble: 4 x 3
##   dgcat     mean median
##   &lt;fct&gt;    &lt;dbl&gt;  &lt;dbl&gt;
## 1 (0,30]    4.24   4.4 
## 2 (30,60]   2.98   3.06
## 3 (60,90]   3.16   2.85
## 4 (90,Inf]  1.69   2.33</code></pre>
<p>This by itself changes the results somewhat (the mean growth rate of the highest indebted group drops from 2.17% to 1.69%) but the differences aren’t all that dramatic. It is the combination of the above and the following third change that result in a dramatic change.</p>
<ol start="3" style="list-style-type: decimal">
<li>Observations are re-weighted according to the following scheme:</li>
</ol>
<pre class="r"><code>RRselective2 &lt;- RRselective %&gt;%
                group_by(dgcat,Country) %&gt;%                           # create category and country groups
                summarize( m1 = mean(dRGDP, na.rm = TRUE)) %&gt;%        # calculate average growth in each category
                group_by(dgcat) %&gt;%                                   # group again by category
                summarize(  n = n(), mean = mean(m1, na.rm = TRUE), median = median(m1, na.rm = TRUE)) %&gt;%  # calculate mean in each category 
                print()</code></pre>
<pre><code>## # A tibble: 4 x 4
##   dgcat        n    mean median
##   &lt;fct&gt;    &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;
## 1 (0,30]      13  4.09     4.00
## 2 (30,60]     15  2.87     2.89
## 3 (60,90]     14  3.40     2.86
## 4 (90,Inf]     7 -0.0242   1.03</code></pre>
<p>Clearly, this scheme delivers clearly lower average and median growth for the highest debt category.</p>
<p>The main difference in this new scheme is that not each country-year receives the same weight. The authors calculate groups of data by <code>dgcat</code> and <code>Country</code> and then calculate average growth rates. That means that for instance France receives one average growth rate for each of the the three lowest debt categories (not in any year did it exceed the 90% threshold) and Germany receives an average growth for the two lowest debt categories (as it never exceeded the 60% threshold in the sample period). Then the country averages in each category are averaged again.</p>
<p>This may seem totally arbitrary and indeed the justification provided by Reinhard and Rogoff seems to be, at best, deficient. Having said that, it is not unreasonable to think carefully about the weighting&gt; previously we saw that there is a lot of persistence in the data. This may be a reason for perhaps not weighting every year as its own, equally weighted, observation.</p>
</div>
<div id="how-to-learn-r" class="section level1">
<h1>How to learn R</h1>
<p>Learning any programming language, and yes, that is what R essentially is, can only be done by doing. Here we are not exposing you to a bottom-up introduction of R, but we are immediately exposing you to the exciting possibilities of R and the beauty and excitement of working with real-life data. As we do so we expose you to the basic tools of working with data in R and help you to learn these.</p>
<p>However, you have to accept from the outset that this is going to be a bumby raod! The most crucial skill you will have to embrace and develop is that of finding solutions to prolems. You will, as any programmer, yes, even the most experienced ones, search the internet for solutions to your problem. Don’t think that you can remember all the important commands from the top of your mind.</p>
<p>Whenever we introduce a new R functionality we will briefly explain it, but importantly we will also give you links to further resources where you can find more usage examples and details. Also do not frget to use the build-in help function in R (type <code>?FUNCTIONNAME</code> into the Console and press Enter). This is important as it is the help that will be available offline as well.</p>
</div>
<div id="r-programming-concepts-used" class="section level1">
<h1>R programming concepts used</h1>
<p>The following R programming concepts were used in this document. The links lead to pages that provide help with these issues.</p>
<ul>
<li>use of packages/libraries: <a href="http://eclr.humanities.manchester.ac.uk/index.php/R_Packages">ECLR</a></li>
<li>importing of data: <a href="http://eclr.humanities.manchester.ac.uk/index.php/R_Data">csv.read</a>, <a href="https://www.datacamp.com/community/tutorials/r-tutorial-read-excel-into-r">read_excel</a></li>
<li>Summarising data: <a href="http://eclr.humanities.manchester.ac.uk/index.php/R_Analysis#Summary_Statistics_-_Take_1">descriptive statistics</a></li>
<li>Plotting data using ggplot: <a href="http://www.cookbook-r.com/Graphs/">Cookbook for R</a>, <a href="https://www.datacamp.com/courses/data-visualization-with-ggplot2-1">free 1st chapter of datacamp interactive tutorial</a></li>
<li>running regressions: <a href="http://eclr.humanities.manchester.ac.uk/index.php/R_Regression">ECLR</a></li>
<li>using the <a href="https://www.jakeruss.com/cheatsheets/stargazer/">stargazer package</a> for summary statistics and regresison output</li>
<li>using the tidverse to produce <a href="http://eclr.humanities.manchester.ac.uk/index.php/R_AnalysisTidy">subsets and groupings of data and summarise these</a></li>
<li>hypothesis tests on sample means, using the <a href="https://www.statmethods.net/stats/ttest.html">t.test function</a></li>
</ul>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
